spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/bookingdb
    username: booking_user
    password: booking_pass

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.liquibase: INFO
